### PR TITLE
fix: fix typo in README prop

### PR DESCRIPTION
**Pull request by poacher2k**

### CODE REVIEW

**Comment by no23reason** [comment]
Hi, @poacher2k, thank you for the fix! Can you please change the commit message of your commit to be compatible with `semantic-release`. I suggest something like:

```
fix: fix typo in README prop
```

Thanks!

**Comment by poacher2k** [comment]
Done!

**Comment by no23reason** [comment]
Merging, thank you for the contribution and the quick update!

**Comment by poacher2k** [comment]
Thank you yourself for this great library! :)

**Pull request merged**
